"""
my-api - 
Auto-generated by Waka API Factory V2
"""
import os
import logging
from functools import wraps
from flask import Flask, jsonify, request

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

from routes.api_routes import api_bp

API_KEY = os.environ.get("API_KEY", "336227ad-e8b9-45fc-827b-c66a719b8d63")


def require_api_key(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        key = request.headers.get("X-API-Key") or request.args.get("api_key")
        if key != API_KEY:
            return jsonify({"error": "Invalid or missing API key"}), 401
        return f(*args, **kwargs)
    return decorated


def create_app():
    app = Flask(__name__)

    # CORS
    @app.after_request
    def add_cors(response):
        response.headers["Access-Control-Allow-Origin"] = "*"
        response.headers["Access-Control-Allow-Headers"] = "Content-Type, X-API-Key"
        response.headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
        return response

    # Health check (no API key required)
    @app.route("/api/health")
    def health():
        return jsonify({"status": "ok", "service": "my-api"})

    app.register_blueprint(api_bp, url_prefix="/api")

    # Apply API key protection to all /api/ routes except health
    for rule in app.url_map.iter_rules():
        if rule.endpoint != "health" and rule.rule.startswith("/api/"):
            view_func = app.view_functions.get(rule.endpoint)
            if view_func and not getattr(view_func, "_api_key_protected", False):
                protected = require_api_key(view_func)
                protected._api_key_protected = True
                app.view_functions[rule.endpoint] = protected

    return app


if __name__ == "__main__":
    app = create_app()
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)))
