"""
Resource Initialization - uses Managed Identity (no keys in code)
Auto-generated by Waka API Factory V2
"""
import os
import logging

logger = logging.getLogger(__name__)


def init_all():
    """Verify all required environment variables are set."""
    required = []

    missing = [v for v in required if not os.environ.get(v)]
    if missing:
        logger.warning(f"Missing env vars: {missing}")
    else:
        logger.info("All required environment variables are set.")
    return missing


if __name__ == "__main__":
    init_all()